Repository influxdata/influxdb-client-php, pull requests merged in 2020-06, with the labels that each got.

#27 feat: Updated swagger to latest version
  CHANGELOG.md
  scripts/swagger.yml
  src/InfluxDB2/Model/HealthCheck.php
  src/InfluxDB2/Model/Query.php
Labels: api

#30 update for php 7.4 compatibility
  .circleci/config.yml
  CHANGELOG.md
  composer.json
  src/InfluxDB2/WriteOptions.php
Labels: enhancement

#28 fix: serialization of `\n`, `\r` and `\t` to Line Protocol, `=` is valid sign for measurement name
  CHANGELOG.md
  src/InfluxDB2/Point.php
  tests/PointTest.php
Labels: bug
